### ISSUE TITLE
How to create art for the Game  

### ISSUE THREAD

**Issue by kokito123-ui** [Haruno19/CustomQuest#1]
I tried to Open the slime.txt file to try to understand how make or edit the monster but i couldnt exist a specific way to do it ? Also when i instaled Custom Quest the Orange and normal slime looked the same

**Comment by Haruno19** [comment]
Hi!  I fixed the Orange Slime not being displayed issue, it was a simple problem with capital letters (the `JSON` files is named `Orange Slime` and the `txt` art was `orange slime`, my bad, now it's fixed).

About how to create the arts, you can do any kind of ASCII art you want, it hasn't got to be in the same format as the Slime or Orange Slime one, as long as it's a `txt` file it's fine. 

`arts/Slime.txt` and `arts/Orange Slime.txt` are done with the escape code `[38;2;R;G;Bm` in which of course you can change RGB to any value between `0` and `255` to color the two Full-Width block characters ██ which simulate a "pixel" of the sprite (I recommend to use two █ characters in order to keep the right proportions, otherwise, the art will look "stretched" horizontally). You can check out more examples of this kind of "RGB colored ASCII arts" [here in my profile repo](https://github.com/Haruno19/Haruno19/tree/main/ASCII%20Arts).
