### ISSUE TITLE
An error occurred while running on macOS

### ISSUE THREAD

**Issue by talwat** [Haruno19/CustomQuest#2]
Hello!

I have encountered this error: `libc++abi: terminating with uncaught exception of type std::out_of_range: basic_string` while running CustomQuest after I compiled it.

**OS**: MacOS 12.3.1
**Arch**: arm64 (M1 Chip)
**Compiler Version**: Apple clang version 13.1.6 (clang-1316.0.21.2.3)

**Comment by Haruno19** [comment]
Hi! Thank you for posting this issue. 
I have a few questions to understand better your situation. 
My guess is that the `std::out_of_range: basic_string` error hints at the fact that CustomQuest doesn't find some of the resource files it needs; I see you compiled with `clang`, instead of `g++` (which is the compiler specified in the `makefile`). How did you compile CustomQuest with `clang`? Did you change the compiler in the `makefile` from `g++` to `clang++` and then ran `sudo make install`? In that case, can you please post the output of `tree /usr/local/share/customquest`?

**Comment by talwat** [comment]
I think the issue may be that it throws an error when it hasn’t been installed, m because needed directories are missing. I just ran it locally, but I will try actually installing it now and see if that fixes it.

**Comment by Haruno19** [comment]
Yeah, that probably is the problem. It expects files in `/use/local/share/customquest` and needs them to work correctly

**Comment by Haruno19** [comment]
Any update on this? Is the issue solved?

**Comment by talwat** [comment]
No, it still happens.
Edit: When I use **make install** it works, but I think it would be useful if you could configure the paths before.

**Comment by Haruno19** [comment]
Ok so, considering it works as expected, I'll close this issue as there are no plans in doing a "portable" version (the path is hardcoded in the source file)
